/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptvpso;

import java.awt.Choice;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


/**
 * Link paper: https://www.researchgate.net/publication/327663876_Optimasi_Pemberian_Pupuk_Dan_Pestisida_Secara_Berkala_Pada_Tanaman_Padi_Dengan_Parallel_Time_Variant_Particle_Swarm_Optimization_PTVPSO
 * @author Mahasiswi a.n. Edelin Yoda Bernadifta 
 * dosbing ke-1: Imam Cholissodin (imamcs@ub.ac.id) sbg Co-Author.
 * dosbing ke-2: Heru Nurwarsito
 * Filkom UB 2016 - 2021
 * sebagai Hilirisasi Teknologi untuk PengMas 2021 
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    private Parameter PM;
    public static int ppk;
    public static double n, p, k, p1, p2, p3, p4, p5;
    public static String pes1, pes2, pes3, pes4, pes5;
    Object[][] hasil;
    String[] namaKolomHasil = {"Iterasi", "Partikel", "NPK", "Urea-1", "SP36-1", "KCL-1", "Urea-2", "Urea-3", "KCL-3", "Pest1", "Pest2",
            "Pest3", "Pest4", "Pest5", "Cost"};
    String[] namaKolomRange = {"Range", "NPK", "Urea-1", "SP36-1", "KCL-1", "Urea-2", "Urea-3", "KCL-3", "Pest1", "Pest2",
            "Pest3", "Pest4", "Pest5"};
    
    public Interface() {
        initComponents();
        AEWERENGCOKLAT.setEnabled(false);
        AEPENGGEREKBATANG.setEnabled(false);
        AEWALANGSANGIT.setEnabled(false);
        AEHAWAR.setEnabled(false);
        AEBERCAKDAUN.setEnabled(false);
        enablePupuk(false);
        enableHara(false);
        
        // set icon
        this.setIconImage(this.getToolkit().createImage("citrus-icon.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrp_pilihanjenispupuk = new javax.swing.ButtonGroup();
        bgrp_kandunganP = new javax.swing.ButtonGroup();
        bgrp_kandunganK = new javax.swing.ButtonGroup();
        bgrp_kandunganN = new javax.swing.ButtonGroup();
        bgrp_jenislahan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LAHANSAWAH = new javax.swing.JRadioButton();
        LAHANKERING = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        box = new javax.swing.JPanel();
        PROSES = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TUNGGAL = new javax.swing.JRadioButton();
        TUNGGALJERAMI = new javax.swing.JRadioButton();
        TUNGGALPPK = new javax.swing.JRadioButton();
        NPK15 = new javax.swing.JRadioButton();
        NPK10 = new javax.swing.JRadioButton();
        NPK30 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NRENDAH = new javax.swing.JRadioButton();
        NSEDANG = new javax.swing.JRadioButton();
        NTINGGI = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        PRENDAH = new javax.swing.JRadioButton();
        PSEDANG = new javax.swing.JRadioButton();
        PTINGGI = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        KRENDAH = new javax.swing.JRadioButton();
        KSEDANG = new javax.swing.JRadioButton();
        KTINGGI = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        WERENGCOKLAT = new javax.swing.JRadioButton();
        PENGGEREKBATANG = new javax.swing.JRadioButton();
        WALANGSANGIT = new javax.swing.JRadioButton();
        HAWAR = new javax.swing.JRadioButton();
        BERCAKDAUN = new javax.swing.JRadioButton();
        AEWERENGCOKLAT = new javax.swing.JComboBox();
        AEPENGGEREKBATANG = new javax.swing.JComboBox();
        AEWALANGSANGIT = new javax.swing.JComboBox();
        AEHAWAR = new javax.swing.JComboBox();
        AEBERCAKDAUN = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        KoefisienK = new javax.swing.JTextField();
        WMIN = new javax.swing.JTextField();
        WMAX = new javax.swing.JTextField();
        C2F = new javax.swing.JTextField();
        C2I = new javax.swing.JTextField();
        C1F = new javax.swing.JTextField();
        C1I = new javax.swing.JTextField();
        MAXITERASI = new javax.swing.JTextField();
        SWARMSIZE = new javax.swing.JTextField();
        setParameterDefault = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RANGEREKOM = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        HASILOPTIMASI = new javax.swing.JTable();
        runningtime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KETERANGAN = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocationByPlatform(true);
        setName("FRAMEUTAMA"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SISTEM OPTIMASI DOSIS PUPUK DAN PESTISIDA SECARA BERKALA PADA TANAMAN PADI BERDASARKAN VARIETAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Lahan  : ");

        bgrp_jenislahan.add(LAHANSAWAH);
        LAHANSAWAH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LAHANSAWAH.setText("Lahan Sawah");
        LAHANSAWAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAHANSAWAHActionPerformed(evt);
            }
        });

        bgrp_jenislahan.add(LAHANKERING);
        LAHANKERING.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LAHANKERING.setText("Lahan Kering");
        LAHANKERING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAHANKERINGActionPerformed(evt);
            }
        });

        box.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PROSES.setText("PROSES");
        PROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROSESActionPerformed(evt);
            }
        });

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilihan Jenis Pupuk"));

        bgrp_pilihanjenispupuk.add(TUNGGAL);
        TUNGGAL.setText("Tunggal");
        TUNGGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNGGALActionPerformed(evt);
            }
        });

        bgrp_pilihanjenispupuk.add(TUNGGALJERAMI);
        TUNGGALJERAMI.setText("Tunggal + jerami");
        TUNGGALJERAMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNGGALJERAMIActionPerformed(evt);
            }
        });

        bgrp_pilihanjenispupuk.add(TUNGGALPPK);
        TUNGGALPPK.setText("Tunggal + pupuk kandang");
        TUNGGALPPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNGGALPPKActionPerformed(evt);
            }
        });

        bgrp_pilihanjenispupuk.add(NPK15);
        NPK15.setText("Tunggal + majemuk phonska 15:15:15");
        NPK15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPK15ActionPerformed(evt);
            }
        });

        bgrp_pilihanjenispupuk.add(NPK10);
        NPK10.setText("Tunggal + majemuk phonska 10:10:10");
        NPK10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPK10ActionPerformed(evt);
            }
        });

        bgrp_pilihanjenispupuk.add(NPK30);
        NPK30.setText("Tunggal + majemuk phonska 30:6:8");
        NPK30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPK30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NPK10)
                    .addComponent(TUNGGALPPK)
                    .addComponent(TUNGGALJERAMI)
                    .addComponent(TUNGGAL)
                    .addComponent(NPK15)
                    .addComponent(NPK30))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TUNGGAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TUNGGALJERAMI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TUNGGALPPK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPK15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPK10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NPK30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status Hara Tanah"));

        jLabel6.setText("Kandungan N");

        bgrp_kandunganN.add(NRENDAH);
        NRENDAH.setText("Rendah");
        NRENDAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NRENDAHActionPerformed(evt);
            }
        });

        bgrp_kandunganN.add(NSEDANG);
        NSEDANG.setText("Sedang");
        NSEDANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSEDANGActionPerformed(evt);
            }
        });

        bgrp_kandunganN.add(NTINGGI);
        NTINGGI.setText("Tinggi");
        NTINGGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTINGGIActionPerformed(evt);
            }
        });

        jLabel7.setText("Kandungan P");

        bgrp_kandunganP.add(PRENDAH);
        PRENDAH.setText("Rendah");
        PRENDAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRENDAHActionPerformed(evt);
            }
        });

        bgrp_kandunganP.add(PSEDANG);
        PSEDANG.setText("Sedang");
        PSEDANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSEDANGActionPerformed(evt);
            }
        });

        bgrp_kandunganP.add(PTINGGI);
        PTINGGI.setText("Tinggi");
        PTINGGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTINGGIActionPerformed(evt);
            }
        });

        jLabel8.setText("Kandungan K");

        bgrp_kandunganK.add(KRENDAH);
        KRENDAH.setText("Rendah");
        KRENDAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KRENDAHActionPerformed(evt);
            }
        });

        bgrp_kandunganK.add(KSEDANG);
        KSEDANG.setText("Sedang");
        KSEDANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KSEDANGActionPerformed(evt);
            }
        });

        bgrp_kandunganK.add(KTINGGI);
        KTINGGI.setText("Tinggi");
        KTINGGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTINGGIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(NRENDAH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(NTINGGI, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSEDANG, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PRENDAH)
                    .addComponent(jLabel7)
                    .addComponent(PSEDANG)
                    .addComponent(PTINGGI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(KSEDANG)
                    .addComponent(KTINGGI)
                    .addComponent(KRENDAH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NRENDAH)
                    .addComponent(PRENDAH)
                    .addComponent(KRENDAH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NSEDANG)
                    .addComponent(PSEDANG)
                    .addComponent(KSEDANG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTINGGI)
                    .addComponent(KTINGGI)
                    .addComponent(NTINGGI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilihan Pestisida"));

        WERENGCOKLAT.setText("Wereng coklat");
        WERENGCOKLAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WERENGCOKLATActionPerformed(evt);
            }
        });

        PENGGEREKBATANG.setText("Penggerek batang");
        PENGGEREKBATANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PENGGEREKBATANGActionPerformed(evt);
            }
        });

        WALANGSANGIT.setText("Walang sangit");
        WALANGSANGIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WALANGSANGITActionPerformed(evt);
            }
        });

        HAWAR.setText("Hawar");
        HAWAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAWARActionPerformed(evt);
            }
        });

        BERCAKDAUN.setText("Bercak daun");
        BERCAKDAUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BERCAKDAUNActionPerformed(evt);
            }
        });

        AEWERENGCOKLAT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AEWERENGCOKLAT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<AE", "=AE", ">AE" }));
        AEWERENGCOKLAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEWERENGCOKLATActionPerformed(evt);
            }
        });

        AEPENGGEREKBATANG.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AEPENGGEREKBATANG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<AE", "=AE", ">AE" }));
        AEPENGGEREKBATANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEPENGGEREKBATANGActionPerformed(evt);
            }
        });

        AEWALANGSANGIT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AEWALANGSANGIT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<AE", "=AE", ">AE" }));
        AEWALANGSANGIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEWALANGSANGITActionPerformed(evt);
            }
        });

        AEHAWAR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AEHAWAR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<AE", "=AE", ">AE" }));
        AEHAWAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEHAWARActionPerformed(evt);
            }
        });

        AEBERCAKDAUN.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AEBERCAKDAUN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<AE", "=AE", ">AE" }));
        AEBERCAKDAUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEBERCAKDAUNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BERCAKDAUN)
                    .addComponent(HAWAR)
                    .addComponent(WALANGSANGIT)
                    .addComponent(PENGGEREKBATANG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WERENGCOKLAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AEBERCAKDAUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEHAWAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEWALANGSANGIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEWERENGCOKLAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEPENGGEREKBATANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEWERENGCOKLAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WERENGCOKLAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEPENGGEREKBATANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PENGGEREKBATANG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEWALANGSANGIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WALANGSANGIT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEHAWAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HAWAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEBERCAKDAUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BERCAKDAUN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter TVPSO"));

        jLabel10.setText("Jumlah partikel");

        jLabel11.setText("Max iterasi");

        jLabel12.setText("Nilai C1i");

        jLabel19.setText("Nilai C1f");

        jLabel13.setText("Nilai C2i");

        jLabel20.setText("Nilai C2f");

        jLabel14.setText("Nilai wMax");

        jLabel15.setText("Nilai wMin");

        jLabel21.setText("Koefisien K");

        KoefisienK.setToolTipText("0-1(desimal)");
        KoefisienK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KoefisienKActionPerformed(evt);
            }
        });

        WMIN.setToolTipText("0-1(desimal), Wmin<Wmax");

        WMAX.setToolTipText("0-1(desimal), Wmax>Wmin");

        C1I.setToolTipText("");

        MAXITERASI.setToolTipText(">3");
        MAXITERASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAXITERASIActionPerformed(evt);
            }
        });

        SWARMSIZE.setToolTipText(">5");
        SWARMSIZE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWARMSIZEActionPerformed(evt);
            }
        });

        setParameterDefault.setText("Set default");
        setParameterDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setParameterDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(setParameterDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KoefisienK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MAXITERASI, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SWARMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C1I, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C1F, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C2I, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C2F, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(SWARMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAXITERASI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C1I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(C1F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C2I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C2F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KoefisienK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setParameterDefault)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Range Solusi dan Hasil Optimasi"));
        jPanel5.setToolTipText("");

        RANGEREKOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Min", null, null, null, null, null, null, null, null, null, null, null, null},
                {"Max", null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Range", "NPK", "Urea-1", "SP36-1", "KCL-1", "Urea-2", "Urea-3", "KCL-3", "Pest 1", "Pest 2", "Pest 3", "Pest 4", "Pest 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(RANGEREKOM);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        HASILOPTIMASI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Iterasi", "Partikel", "NPK", "Urea-1", "SP36-1", "KCL-1", "Urea-2", "Urea-3", "KCL-3", "Pest1", "Pest2", "Pest3", "Pest4", "Pest5", "Cost"
            }
        ));
        jScrollPane2.setViewportView(HASILOPTIMASI);
        if (HASILOPTIMASI.getColumnModel().getColumnCount() > 0) {
            HASILOPTIMASI.getColumnModel().getColumn(14).setPreferredWidth(160);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Running time sistem :");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptvpso/gbrf.png"))); // NOI18N

        javax.swing.GroupLayout boxLayout = new javax.swing.GroupLayout(box);
        box.setLayout(boxLayout);
        boxLayout.setHorizontalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, boxLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(PROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runningtime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boxLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(boxLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        boxLayout.setVerticalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runningtime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RESET)
                        .addComponent(PROSES)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data sistem", box);
        box.getAccessibleContext().setAccessibleParent(box);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Detaill Kebutuhan Dosis Optimal"));

        KETERANGAN.setColumns(20);
        KETERANGAN.setRows(5);
        jScrollPane1.setViewportView(KETERANGAN);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Penjelasan Penggunaan"));

        jTextArea1.setBackground(new java.awt.Color(230, 229, 229));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("  Pemupukan Berimbang Tanaman Padi\n  Pemupukan berimbang diberikan dalam 3 tahap pemupukan \n  1. Pemupukan Dasar, saat padi memasuki 0-14 HST (Hari Setelah Tanam)\n  2. Pemupukan Susulan 1, saat padi memasuki 21-28 HST (Hari Setelah Tanam)\n  3. Pemupukan Susulan 2, saat padi memasuki 35-50 HST (Hari Setelah Tanam)\n  Dosis yang dihasilkan oleh sistem ini telah memperhatikan kandungan unsur hara tanah,oleh karena \n  itu pengujian kandungan tanah diperlukan. Pengujian menggunakan PUTS(Perangkat Uji Tanah Sawah)\n\n  Konsep PHT (Pengendalian Hama Terpadu)\n  Mengingat pestisida merupakan bahan kimia berbahaya maka penggunaan pestisida merupakan \n  komponen pengendalian yang dilakukan, JIKA : \n  1. Populasi hama telah meninggalkan populasi musuh alami, sehingga tidak mampu dalam waktu \n      singkat menekan populasi hama.\n  2. Komponen-komponen pengendalian alami lainnya tidak dapat mengatasi \n  3. Keadaan populasi hama sangat mendekati sampai melebihi Ambang Ekonomi(AE), yaitu batas  \n      populasi hama telah  menimbulkan kerusakan yang lebih besar daripada biaya pengendalian.\n      AE Penggerek batang padi : 1 kelompok telur /m2 atau intesitas serangan rata-rata 10%\n      AE Wereng pada padi : Wereng punggung putih pada padi\n      AE Walang sangit padi : 5 ekor /m2 pada tahap tanaman setelah berbunga");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Keterangan hasill", jPanel6);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("(Optimasi Pupuk dan Pestisida Dgn TVPSO)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LAHANSAWAH)
                                .addGap(18, 18, 18)
                                .addComponent(LAHANKERING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LAHANSAWAH)
                    .addComponent(LAHANKERING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LAHANSAWAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAHANSAWAHActionPerformed
        // TODO add your handling code here:
        TUNGGAL.setEnabled(true);
        TUNGGALJERAMI.setEnabled(true);
        TUNGGALPPK.setEnabled(true);
        NPK10.setEnabled(true);
        NPK15.setEnabled(true);
        NPK30.setEnabled(true);
        bgrp_pilihanjenispupuk.clearSelection();
    }//GEN-LAST:event_LAHANSAWAHActionPerformed
    
    private void LAHANKERINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAHANKERINGActionPerformed
        // TODO add your handling code here:
        TUNGGAL.setEnabled(false);
        TUNGGALJERAMI.setEnabled(false);
        TUNGGALPPK.setEnabled(true);
        NPK10.setEnabled(false);
        NPK15.setEnabled(false);
        NPK30.setEnabled(false);
    }//GEN-LAST:event_LAHANKERINGActionPerformed

    private void SWARMSIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWARMSIZEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SWARMSIZEActionPerformed

    private void MAXITERASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAXITERASIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAXITERASIActionPerformed

    private void KoefisienKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KoefisienKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KoefisienKActionPerformed

    private void AEBERCAKDAUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEBERCAKDAUNActionPerformed
        // TODO add your handling code here:
        if (AEBERCAKDAUN.getSelectedIndex()==0) {
            p5 = 0.5;
        }else {
            p5 = 1;
        }
    }//GEN-LAST:event_AEBERCAKDAUNActionPerformed

    private void AEHAWARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEHAWARActionPerformed
        // TODO add your handling code here:
        if (AEHAWAR.getSelectedIndex()==0) {
            p4 = 0.25;
        }  else {
            p4 = 0.5;
        } 
    }//GEN-LAST:event_AEHAWARActionPerformed

    private void AEWALANGSANGITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEWALANGSANGITActionPerformed
        // TODO add your handling code here:
        if (AEWALANGSANGIT.getSelectedIndex()==0) {
            p3 = 0.2;
        } else {
            p3 = 0.4;
        }
    }//GEN-LAST:event_AEWALANGSANGITActionPerformed

    private void AEPENGGEREKBATANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEPENGGEREKBATANGActionPerformed
        // TODO add your handling code here:
        if (AEPENGGEREKBATANG.getSelectedIndex()==0) {
            p2 = 0.75;
        } else  {
            p2 = 1;
        } 
    }//GEN-LAST:event_AEPENGGEREKBATANGActionPerformed

    private void AEWERENGCOKLATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEWERENGCOKLATActionPerformed
        // TODO add your handling code here:
        if (AEWERENGCOKLAT.getSelectedIndex()==0) {
            p1 = 0.5;
        } else {
            p1 = 1;
        } 
    }//GEN-LAST:event_AEWERENGCOKLATActionPerformed

    private void BERCAKDAUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BERCAKDAUNActionPerformed
        // TODO add your handling code here:
        if (BERCAKDAUN.isSelected()) {
            pes5 = "y";
            AEBERCAKDAUN.setEnabled(true);
        } else {
            AEBERCAKDAUN.setEnabled(false);
        }
    }//GEN-LAST:event_BERCAKDAUNActionPerformed

    private void HAWARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAWARActionPerformed
        // TODO add your handling code here:
        if (HAWAR.isSelected()) {
            pes4 = "y";
            AEHAWAR.setEnabled(true);
        } else {
            AEHAWAR.setEnabled(false);
        }
    }//GEN-LAST:event_HAWARActionPerformed

    private void WALANGSANGITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WALANGSANGITActionPerformed
        // TODO add your handling code here:
        if (WALANGSANGIT.isSelected()) {
            pes3 = "y";
            AEWALANGSANGIT.setEnabled(true);
        } else {
            AEWALANGSANGIT.setEnabled(false);
        }
    }//GEN-LAST:event_WALANGSANGITActionPerformed

    private void PENGGEREKBATANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PENGGEREKBATANGActionPerformed
        // TODO add your handling code here:
        if (PENGGEREKBATANG.isSelected()) {
            pes2 = "y";
            AEPENGGEREKBATANG.setEnabled(true);
        } else {
            AEPENGGEREKBATANG.setEnabled(false);
        }
    }//GEN-LAST:event_PENGGEREKBATANGActionPerformed

    private void WERENGCOKLATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WERENGCOKLATActionPerformed
        // TODO add your handling code here:
        if (WERENGCOKLAT.isSelected()) {
            pes1 = "y";
            AEWERENGCOKLAT.setEnabled(true);
             AEWERENGCOKLATActionPerformed(evt);
        } else {
            AEWERENGCOKLAT.setEnabled(false);
        }
    }//GEN-LAST:event_WERENGCOKLATActionPerformed

    private void KTINGGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTINGGIActionPerformed
        // TODO add your handling code here:
            k = 30;
    }//GEN-LAST:event_KTINGGIActionPerformed

    private void KSEDANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KSEDANGActionPerformed
        // TODO add your handling code here:
            k = 45;
    }//GEN-LAST:event_KSEDANGActionPerformed

    private void KRENDAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KRENDAHActionPerformed
        // TODO add your handling code here:
            k = 60;
    }//GEN-LAST:event_KRENDAHActionPerformed

    private void PTINGGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTINGGIActionPerformed
        // TODO add your handling code here:
            p = 18;
    }//GEN-LAST:event_PTINGGIActionPerformed

    private void PSEDANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSEDANGActionPerformed
        // TODO add your handling code here:
            p = 27;
    }//GEN-LAST:event_PSEDANGActionPerformed

    private void PRENDAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRENDAHActionPerformed
        // TODO add your handling code here:
            p = 45;
    }//GEN-LAST:event_PRENDAHActionPerformed

    private void NTINGGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTINGGIActionPerformed
        // TODO add your handling code here:
            n = 109;
    }//GEN-LAST:event_NTINGGIActionPerformed

    private void NSEDANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSEDANGActionPerformed
        // TODO add your handling code here:
            n = 112.5;
    }//GEN-LAST:event_NSEDANGActionPerformed

    private void NRENDAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NRENDAHActionPerformed
        // TODO add your handling code here:
            n = 135;
    }//GEN-LAST:event_NRENDAHActionPerformed

    private void NPK30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPK30ActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && NPK30.isSelected()) {
            ppk = 6;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_NPK30ActionPerformed

    private void NPK10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPK10ActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && NPK10.isSelected()) {
            ppk = 5;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_NPK10ActionPerformed

    private void NPK15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPK15ActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && NPK15.isSelected()) {
            ppk = 4;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_NPK15ActionPerformed

    private void TUNGGALPPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNGGALPPKActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && TUNGGALPPK.isSelected()) {
            ppk = 3;
            enableHara(true);
        } else if (LAHANKERING.isSelected() && TUNGGALPPK.isSelected()) {
            ppk = 7;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_TUNGGALPPKActionPerformed

    private void TUNGGALJERAMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNGGALJERAMIActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && TUNGGALJERAMI.isSelected()) {
            ppk = 2;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_TUNGGALJERAMIActionPerformed

    private void TUNGGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNGGALActionPerformed
        // TODO add your handling code here:
        if (LAHANSAWAH.isSelected() && TUNGGAL.isSelected()) {
            ppk = 1;
            enableHara(true);
        } else {
        }
    }//GEN-LAST:event_TUNGGALActionPerformed

    private void setParameterDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setParameterDefaultActionPerformed
        // TODO add your handling code here:
        SWARMSIZE.setText("15");
        MAXITERASI.setText("5");
        C1I.setText("2.5");
        C1F.setText("0.5");
        C2I.setText("0.5");
        C2F.setText("2.5");
        WMAX.setText("0.9");
        WMIN.setText("0.4");
        KoefisienK.setText("0.6");
    }//GEN-LAST:event_setParameterDefaultActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed

        BERCAKDAUN.setSelected(false);
        WERENGCOKLAT.setSelected(false);
        PENGGEREKBATANG.setSelected(false);
        WALANGSANGIT.setSelected(false);
        HAWAR.setSelected(false);
        AEBERCAKDAUN.setEnabled(false);
        AEHAWAR.setEnabled(false);
        AEPENGGEREKBATANG.setEnabled(false);
        AEWALANGSANGIT.setEnabled(false);
        AEWERENGCOKLAT.setEnabled(false);
        bgrp_jenislahan.clearSelection();
        bgrp_pilihanjenispupuk.clearSelection();
        bgrp_kandunganN.clearSelection();
        bgrp_kandunganP.clearSelection();
        bgrp_kandunganK.clearSelection();
        MAXITERASI.setText("");
        SWARMSIZE.setText("");
        C1I.setText("");
        C1F.setText("");
        C2I.setText("");
        C2F.setText("");
        WMAX.setText("");
        WMIN.setText("");
        KoefisienK.setText("");
        KETERANGAN.setText("");
        enablePupuk(false);
        enableHara(false);
        Object[][] isirange = new Object[2][13];
        Object[][] isihasil = new Object[0][15];
        setToTable(isihasil, namaKolomHasil, HASILOPTIMASI, jScrollPane2);
        setToTable(isirange, namaKolomRange, RANGEREKOM, jScrollPane3);
    }//GEN-LAST:event_RESETActionPerformed

    private void PROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROSESActionPerformed
        // TODO add your handling code here:
        double start = System.currentTimeMillis();
        new ProblemSet().cekGen(ppk);
        new ProblemSet().cekPest(pes1, pes2, pes3, pes4, pes5);
        new ProblemSet().set(ppk, n, p, k, p1, p2, p3, p4, p5);
        setTableRange();
        setParameter();
        setHasil();
        double finish = System.currentTimeMillis();
        double rt = (finish-start);
        runningtime.setText( rt+" ms");
    }//GEN-LAST:event_PROSESActionPerformed
    
    private void enablePupuk(boolean b){
        TUNGGAL.setEnabled(b);
        TUNGGALJERAMI.setEnabled(b);
        TUNGGALPPK.setEnabled(b);
        NPK10.setEnabled(b);
        NPK15.setEnabled(b);
        NPK30.setEnabled(b);
    }
    
    private void enableHara(boolean b){
        NRENDAH.setEnabled(b);
        NSEDANG.setEnabled(b);
        NTINGGI.setEnabled(b);
        PRENDAH.setEnabled(b);
        PSEDANG.setEnabled(b);
        PTINGGI.setEnabled(b);
        KRENDAH.setEnabled(b);
        KSEDANG.setEnabled(b);
        KTINGGI.setEnabled(b);
    }
    
    private void setParameter() {
        String kesalahan = "";        
        
        try {
            Parameter.setSWARM_SIZE(Integer.parseInt(SWARMSIZE.getText()));
        } catch (Exception e) {
            kesalahan += "Jumlah Partikel";
        }
        try {
            Parameter.setMAX_ITERATION(Integer.parseInt(MAXITERASI.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", MaxIterasi";
            } else {
                kesalahan += "Max Iterasi";
            }            
        }
        try {
            Parameter.setC1f(Double.parseDouble(C1F.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", C1f";
            } else {
                kesalahan += "C1f";
            }            
        }
        try {
            Parameter.setC1i(Double.parseDouble(C1I.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", C1i";
            } else {
                kesalahan += "C1i";
            }            
        }
        try {
            Parameter.setC2f(Double.parseDouble(C2F.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", C2f";
            } else {
                kesalahan += "C2f";
            }            
        }
        try {
            Parameter.setC2i(Double.parseDouble(C2I.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", C2i";
            } else {
                kesalahan += "C2i";
            }            
        }
        try {
            Parameter.setW_MAX(Double.parseDouble(WMAX.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", Wmax";
            } else {
                kesalahan += "Wmax";
            }            
        }
        try {
            Parameter.setW_MIN(Double.parseDouble(WMIN.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", Wmin";
            } else {
                kesalahan += "Wmin";
            }            
        }
        try {
            Parameter.setK(Double.parseDouble(KoefisienK.getText()));
        } catch (Exception e) {
            if (!"".equals(kesalahan)) {
                kesalahan += ", Koefisien K";
            } else {
                kesalahan += "Koefisien K";
            }            
        }
    }
    
    public void setTableRange() {
//      -----Batas bawah-----
        RANGEREKOM.setValueAt("Min", 0, 0);
        for (int j = 0; j < Parameter.getPROBLEM_DIMENSION(); j++) {
            RANGEREKOM.setValueAt(ProblemSet.min[j], 0, j + 1);
        }
//      -----Batas atas-----
        RANGEREKOM.setValueAt("Max", 1, 0);
        for (int j = 0; j < Parameter.getPROBLEM_DIMENSION(); j++) {
            RANGEREKOM.setValueAt(ProblemSet.max[j], 1, j + 1);
        }
    }
    
    public void setHasil() {
        proses po = new proses();
        po.execute();
//        
//        for(int i=0; i<Parameter.getMAX_ITERATION(); i++){
//            HASILOPTIMASI.setValueAt(i, i, 0);
//        }
        
        int length = po.hasilIterasi.size();
//        for (int i = 0; i < length; i++) {
//            HASILOPTIMASI.setValueAt(po.hasilIterasi.get(i).partikel, i, 1);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).NPK), i, 2);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).urea_1), i, 3);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).sp36_1), i, 4);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).kcl_1), i, 5);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).urea_2), i, 6);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).urea_3), i, 7);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).kcl_3), i, 8);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).pest_1), i, 9);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).pest_2), i, 10);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).pest_3), i, 11);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).pest_4), i, 12);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).pest_5), i, 13);
//            HASILOPTIMASI.setValueAt(po.bulat(po.hasilIterasi.get(i).cost), i, 14);
//        }
        
        hasil = new Object[length][15];
        for (int i = 0; i < length; i++) {
            hasil[i][0] = (i + 1);
            hasil[i][1] = po.hasilIterasi.get(i).partikel;
            hasil[i][2] = po.bulat(po.hasilIterasi.get(i).NPK);
            hasil[i][3] = po.bulat(po.hasilIterasi.get(i).urea_1);
            hasil[i][4] = po.bulat(po.hasilIterasi.get(i).sp36_1);
            hasil[i][5] = po.bulat(po.hasilIterasi.get(i).kcl_1);
            hasil[i][6] = po.bulat(po.hasilIterasi.get(i).urea_2);
            hasil[i][7] = po.bulat(po.hasilIterasi.get(i).urea_3);
            hasil[i][8] = po.bulat(po.hasilIterasi.get(i).kcl_3);
            hasil[i][9] = po.bulat(po.hasilIterasi.get(i).pest_1);
            hasil[i][10] = po.bulat(po.hasilIterasi.get(i).pest_2);
            hasil[i][11] = po.bulat(po.hasilIterasi.get(i).pest_3);
            hasil[i][12] = po.bulat(po.hasilIterasi.get(i).pest_4);
            hasil[i][13] = po.bulat(po.hasilIterasi.get(i).pest_5);
            hasil[i][14] = po.bulat(po.hasilIterasi.get(i).cost);
        }
        
        setToTable(hasil, namaKolomHasil, HASILOPTIMASI, jScrollPane2);
        
        String textKeterangan = "-----------Komposisi dosis pupuk optimal-----------\n"
                + " Pupuk Dasar :\n ";
        for (int i = 2; i <= 5; i++) {
            if (Double.parseDouble(hasil[length - 1][i].toString()) > 0.0) {
                textKeterangan += namaKolomHasil[i] + " " + hasil[length - 1][i] + " kg\n ";
            }            
        }
        textKeterangan += "\n Pupuk Susulan Pertama :\n ";
        if (Double.parseDouble(hasil[length - 1][6].toString()) > 0.0) {
            textKeterangan += namaKolomHasil[6] + " " + hasil[length - 1][6] + " kg\n ";
        }        
        textKeterangan += "\n Pupuk Susulan Kedua :\n ";        
        for (int i = 7; i <= 8; i++) {
            if (Double.parseDouble(hasil[length - 1][i].toString()) > 0.0) {
                textKeterangan += namaKolomHasil[i] + " " + hasil[length - 1][i] + " kg\n ";
            }            
        }
        textKeterangan += "\n-----Komposisi konsentrasi pestisida optimal-----\n";
        if (Double.parseDouble(hasil[length - 1][9].toString()) > 0.0) {
            textKeterangan += " Pestisida Wereng Coklat :\n "
                    + "Bahan aktif : Dimehipo 290 g/l \n "
                    + "Nama dagang : Spartan 290 SL \n ";
            textKeterangan += "Konsentrasi  : " + hasil[length - 1][9] + " ml/l\n ";
        }        
        if (Double.parseDouble(hasil[length - 1][10].toString()) > 0.0) {
            textKeterangan += "\n Pestisida Penggerek Batang :\n "
                    + "Bahan aktif : BPMC 500g/l \n "
                    + "Nama dagang : Greta 500 EC \n ";
            textKeterangan += "Konsentrasi  : " + hasil[length - 1][10] + " ml/l\n ";
        }
        if (Double.parseDouble(hasil[length - 1][11].toString()) > 0.0) {
            textKeterangan += "\n Pestisida Walang Sangit :\n "
                    + "Bahan aktif : Imidakloprid 10% \n "
                    + "Nama dagang : Klopindo 10 WP \n ";
            textKeterangan += "Konsentrasi  : " + hasil[length - 1][11] + " ml/l\n ";
        }
        if (Double.parseDouble(hasil[length - 1][12].toString()) > 0.0) {
            textKeterangan += "\n Pestisida Hawar :\n "
                    + "Bahan aktif : Bakterisida \n "
                    + "Nama dagang : Indokor 250 EC \n ";
            textKeterangan += "Konsentrasi  : " + hasil[length - 1][12] + " ml/l\n ";
        }
        if (Double.parseDouble(hasil[length - 1][13].toString()) > 0.0) {
            textKeterangan += "\n Pestisida Bercak Daun :\n "
                    + "Bahan aktif : Bakterisida \n "
                    + "Nama dagang : Indokor 250 EC \n ";
            textKeterangan += "Konsentrasi  : " + hasil[length - 1][13] + " ml/l\n ";
        }
        
        KETERANGAN.setText(textKeterangan);
        
    }

    private void setToTable(Object[][] isiTabel, String[] namaKolom, JTable tabel, JScrollPane scrollPane) {
        tabel.setModel(new javax.swing.table.DefaultTableModel(isiTabel, namaKolom));
        scrollPane.setViewportView(tabel);
        
        sesuaikanKolom(tabel);        
    }
    
    public void sesuaikanKolom(JTable t) {
        //cara untuk menyesuaikan kolom dari tabel adalah mengambil
        // lebar kolom yang ada kemudian sesuaikan
        TableColumnModel modelKolom = t.getColumnModel();
        
        for (int kol = 0; kol < modelKolom.getColumnCount(); kol++) {
            int lebarKolomMax = 0;
            for (int baris = 0; baris < t.getRowCount(); baris++) {
                TableCellRenderer rend = t.getCellRenderer(baris, kol);
                Object nilaiTablel = t.getValueAt(baris, kol);
                Component comp = rend.getTableCellRendererComponent(t, nilaiTablel, false, false, baris, kol);
                lebarKolomMax = Math.max(comp.getPreferredSize().width, lebarKolomMax);
            }//akhir for baris
            TableColumn kolom = modelKolom.getColumn(kol);
            kolom.setPreferredWidth(lebarKolomMax);
        }//akhir for kolom
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Interface().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AEBERCAKDAUN;
    private javax.swing.JComboBox AEHAWAR;
    private javax.swing.JComboBox AEPENGGEREKBATANG;
    private javax.swing.JComboBox AEWALANGSANGIT;
    private javax.swing.JComboBox AEWERENGCOKLAT;
    private javax.swing.JRadioButton BERCAKDAUN;
    private javax.swing.JTextField C1F;
    private javax.swing.JTextField C1I;
    private javax.swing.JTextField C2F;
    private javax.swing.JTextField C2I;
    private javax.swing.JTable HASILOPTIMASI;
    private javax.swing.JRadioButton HAWAR;
    private javax.swing.JTextArea KETERANGAN;
    private javax.swing.JRadioButton KRENDAH;
    private javax.swing.JRadioButton KSEDANG;
    private javax.swing.JRadioButton KTINGGI;
    private javax.swing.JTextField KoefisienK;
    private javax.swing.JRadioButton LAHANKERING;
    private javax.swing.JRadioButton LAHANSAWAH;
    private javax.swing.JTextField MAXITERASI;
    private javax.swing.JRadioButton NPK10;
    private javax.swing.JRadioButton NPK15;
    private javax.swing.JRadioButton NPK30;
    private javax.swing.JRadioButton NRENDAH;
    private javax.swing.JRadioButton NSEDANG;
    private javax.swing.JRadioButton NTINGGI;
    private javax.swing.JRadioButton PENGGEREKBATANG;
    private javax.swing.JRadioButton PRENDAH;
    private javax.swing.JButton PROSES;
    private javax.swing.JRadioButton PSEDANG;
    private javax.swing.JRadioButton PTINGGI;
    private javax.swing.JTable RANGEREKOM;
    private javax.swing.JButton RESET;
    private javax.swing.JTextField SWARMSIZE;
    private javax.swing.JRadioButton TUNGGAL;
    private javax.swing.JRadioButton TUNGGALJERAMI;
    private javax.swing.JRadioButton TUNGGALPPK;
    private javax.swing.JRadioButton WALANGSANGIT;
    private javax.swing.JRadioButton WERENGCOKLAT;
    private javax.swing.JTextField WMAX;
    private javax.swing.JTextField WMIN;
    private javax.swing.ButtonGroup bgrp_jenislahan;
    private javax.swing.ButtonGroup bgrp_kandunganK;
    private javax.swing.ButtonGroup bgrp_kandunganN;
    private javax.swing.ButtonGroup bgrp_kandunganP;
    private javax.swing.ButtonGroup bgrp_pilihanjenispupuk;
    private javax.swing.JPanel box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel runningtime;
    private javax.swing.JToggleButton setParameterDefault;
    // End of variables declaration//GEN-END:variables
}

